language: go
go:
  - 1.11

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | GO111MODULE=on bash
  on:
    tags: true
    condition: $TRAVIS_BRANCH = rewrite
